### ISSUE TITLE
Issue Compiling SpacialOS Fork of Unreal Engine in Visual Studio 2019 

### ISSUE THREAD

**Issue by stephensamonte** [stephensamonte/Unreal-Virginia-Tech#62]
Set up for Visual Studio 2019 can be found here: 
https://documentation.improbable.io/gdk-for-unreal/docs/get-started-1-get-the-dependencies

Set up the fork and plugin:
https://documentation.improbable.io/gdk-for-unreal/docs/get-started-2-set-up-the-fork-and-plugin

Last step build is the last command that was run:
![image](https://user-images.githubusercontent.com/30998408/77858080-359ef400-71cf-11ea-9906-71be9355ca53.png)

```
Severity Code Description Project File Line Suppression State Error MSB3075 The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command. UE4 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets 44
```

![image](https://user-images.githubusercontent.com/30998408/77858029-f5d80c80-71ce-11ea-974c-78e22fbfc3e7.png)

**Comment by stephensamonte** [comment]
The metahost.h file exists in `.Net Framework SDK 4.6.1`

https://docs.microsoft.com/en-us/archive/blogs/calvin_hsia/cannot-open-include-file-metahost-h-no-such-file-or-directory

https://social.msdn.microsoft.com/Forums/en-US/1edd7b3f-478a-4a61-867b-05738839e8b7/vs-2017-and-metahosth?forum=vcgeneral

A comment says:
"""
Actually in my vs2017 win10, metahost.h is located in this folder.

C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Include\um

Firstly, you should check if metahost.h exists in your computer.

If not, please modify your vs2017 and add .Net Framework SDK 4.6.1 feature as blog suggests.
"""

To resolve the issue add the: `.Net Framework SDK 4.6.1` or the specified Framework SDK needed. 

Modify: 
![image](https://user-images.githubusercontent.com/30998408/77864133-f5526c80-71f4-11ea-9b02-9b8abd9fc8e6.png)

Add this: 
![image](https://user-images.githubusercontent.com/30998408/77864149-10bd7780-71f5-11ea-8ef5-186e78186d31.png)

After building with Unreal Engine in Visual Studio: 

![image](https://user-images.githubusercontent.com/30998408/77863997-40b84b00-71f4-11ea-8776-7b2e2329fa2d.png)

**Comment by asmarf6** [comment]
I already have .Net framework 4.6.1 SDK installed but still I get this error. I am building it with VS 2017 and the UE4 version is 4.2.4.1 .Any other step to follow?
